---

- include: generate.yml
  tags:
    - generate-firewall-rules
    - create-rules

- include: scripts.yml
  tags:
    - generate-firewall-rules
    - firewall-scripts 

- include: services.yml
  tags:
    - generate-firewall-rules
    - firewall-service
 
